### ISSUE TITLE
Signup Form - No Success Message \ Icon appearance

### ISSUE THREAD

**Issue by hutch78** [Code-Pop/vue-mastery#15]
Browser: Chrome 64.0.3282.186 on OSX 

When you submit the signup form, there is no success confirmation of any sort - the modal disappears but there is no messaging to tell the user to go check their email. 

Also, is this the intended appearance of this icon in the top right?
 https://www.dropbox.com/s/j1c3dsgfgj0xg3m/Screenshot%202018-03-08%2015.35.24.png?dl=0

On the home page, the `img` inside `.navbar-profile` needs some sort of a background. If it were me, I would put `background-color: #ffffff` on the `<a>` that contains the light gray avatar icon :)

**Comment by pieer** [comment]
Thanks for your feedback Jeremy.

I've added a background image color for the avatar.

There is no need for email confirmation at the moment.
So once you're log in, the modal disappears and the menu is directly switch with your image if you use google or github sign in button or the default avatar picture otherwise.

I understand your feeling about not having any confirmation messages that make it clear that you are now logged in.

@Gregg my suggestion would be to either display a successful message in the popup then after few seconds, make the modal disappear or make the modal disappear and use toasts notifications to say: "You can customise your profile by clicking this link [next to the avatar]" or "you can check your dashboard and lessons completed using this link [next to dashboard link]"

**Comment by Gregg** [comment]
Let's have something come up and say: 

"You are now logged in.  

You can now view your course progress on your dashboard."  Dashboard should be linked.

I was tempted to have it point towards the new Dashboard link, but they could be halfway down the page when they login.  The dashboard link may not be available.

Dustin or Pierre can you try your hand at this?

**Comment by whosdustin** [comment]
@pieer could you add the toast notifications feature to the project.
