### ISSUE TITLE
Add "Congratulations model" with "Share your accomplishment" at end of completed course

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#79]
At the moment if logged in we have one option at the end of the video "Next Video" on the modal that pops up. 

![image](https://user-images.githubusercontent.com/2618/38263284-b69b4b2c-373d-11e8-8982-4d859f1af3aa.png)

Remember how on Code School people would constantly tweet about their accomplishments?  

I'd like to have Dustin design a congratulations modal which comes up at the end of a completed course, which encourages people to share their accomplishment.

Title: Congratulations

Text: You've completed our Intro to Vue.js Course, and earned this completion badge.  Click here to share your accomplishment on your twitter account.

Image: The badge

Tweet pop up: I've reached a milestone on my Journey to Vue Mastery by completing the Intro to Vue.js course on @vuemastery.  <url to the course>

**Comment by Gregg** [comment]
Just adding these notes to make sure things get polished. I know you're still working on it. =) 

- [ ] On staging when I clicked off all checkboxes (including tabs) then watched forms until the end of the video this popped up.  I guess we'll need to ensure only one modal pops up.

![image](https://user-images.githubusercontent.com/2618/39705303-48159004-520e-11e8-96e6-48e6a3153a25.png)

- [ ] Ensure that confetti goes away.  When finishing the course as above, and I clicked away, the confetti never stopped.  It was confetti forever.

- [ ] When someone clicks off all checkboxes (even if they don't make it to the end of a video) they should get congratulations modal.

**Comment by whosdustin** [comment]
I'm happy with my congrats modal design. Until other issues are raised. The last 2 checkboxes in @Gregg s comment are functionality driven and will need some help from @pieer  to complete those pieces. Assigning to @pieer now.

Will need to:
- [ ] Add social share text to the corresponding buttons (reference TODO in the code)
- [ ] Add redirect method to any navigation links in order to prevent confetti from displaying on other pages (reference TODO in the code)
- [ ]  The final 2 checkboxes in @Gregg s comment above
in order to finish the task.
